- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Configure release drafter to keep new release notes up to date.
> Configure release drafter

- .github/release-drafter.yml
- .github/workflows/pr-maintenance.yml
- .github/workflows/release-drafter.yml
> Add PR labelling validation workflow

- infrastructure/warehouse/main.tf
> More warehouse dataset to EU

- services/analyse/src/Service/Publisher/Github/GithubPullRequestCommentPublisherService.php
- services/analyse/tests/Service/Publisher/Github/GithubPullRequestCommentPublisherServiceTest.php
Pull request comments are consistently duplicated at the moment. This PR fixes that.
> Fix bug causing pull request comments to always be posted new

- services/analyse/phpunit.xml.dist
- services/analyse/tests/Handler/EventHandlerTest.php
- services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
- services/analyse/tests/Service/QueryServiceTest.php
- services/api/phpunit.xml.dist
- services/api/src/Command/InvokeEventCommand.php
- services/api/src/Exception/GraphException.php
- services/api/src/Exception/SigningException.php
- services/api/src/Model/GraphParameters.php
- services/api/src/Model/SigningParameters.php
- services/api/src/Repository/ProjectRepository.php
- services/api/tests/Command/InvokeEventCommandTest.php
- services/api/tests/Command/NewProjectCommandTest.php
- services/api/tests/Controller/GraphControllerTest.php
- services/api/tests/Handler/EventHandlerTest.php
- services/api/tests/Model/GraphParametersTest.php
- services/api/tests/Model/SigningParametersTest.php
- services/ingest/tests/Handler/EventHandlerTest.php
- services/ingest/tests/Service/CoverageFileParserServiceTest.php
> Improve tests across services

- packages/models/src/Enum/LineType.php
- packages/models/src/Model/Coverage.php
- packages/models/src/Model/File.php
- services/ingest/src/Service/BigQueryMetadataBuilderService.php
- services/ingest/src/Service/Persist/BigQueryPersistService.php
- services/ingest/src/Service/Persist/S3PersistService.php
- services/ingest/tests/Service/BigQueryMetadataBuilderServiceTest.php
- services/ingest/tests/Service/Persist/BigQueryPersistServiceTest.php
- services/ingest/tests/Service/Persist/S3PersistServiceTest.php
> Refactor persist services to stream content into storage

- services/ingest/src/Service/Persist/S3PersistService.php
- services/ingest/tests/Service/Persist/S3PersistServiceTest.php
> Fix S3 upload not succeeding because of generator terminating

- services/ingest/src/Service/Persist/S3PersistService.php
> Fix S3 generator early termination

- services/ingest/src/Service/Persist/S3PersistService.php
> Try returning the yield from

- services/ingest/src/Service/Persist/S3PersistService.php
- services/ingest/tests/Service/Persist/S3PersistServiceTest.php
> Use a resource and temp memory for streaming to S3

- services/analyse/src/Service/Formatter/PullRequestCommentFormatterService.php
> Update timezone abbreviation on PR comments to UTC

- services/ingest/infrastructure/ingest/main.tf
Increase the max timeout of the ingestion service to support much larger coverage files
> Bump the ingest service timeout to two minutes

- services/ingest/infrastructure/ingest/main.tf
- services/ingest/src/Service/Persist/BigQueryPersistService.php
> Increase throughput to BigQuery

- services/ingest/infrastructure/ingest/main.tf
> Increase memory limit for ingest service

- .github/workflows/analyse.yml
- packages/clients/src/Client/Github/GithubAppClient.php
> Inject the app id for github into the analyse service

- services/analyse/infrastructure/analyse/main.tf
> Update the permissions for the analyse service

- packages/models/src/Model/PublishableMessage/PublishableCheckRunMessage.php
> Fix nullability of check annotations

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> Ability to skip changelogs and better label validation

- .github/workflows/release-drafter.yml
> Only run label validation on PRs

- infrastructure/warehouse/main.tf
> Add total line count into bigquery dataset

- services/ingest/src/Service/BigQueryMetadataBuilderService.php
- services/ingest/src/Service/Persist/BigQueryPersistService.php
- services/ingest/tests/Service/BigQueryMetadataBuilderServiceTest.php
- services/ingest/tests/Service/Persist/BigQueryPersistServiceTest.php
> [Part 2] Persist line count into BigQuery table

- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Fix uploads aggregation

- services/ingest/src/Service/Persist/BigQueryPersistService.php
- services/ingest/tests/Service/Persist/BigQueryPersistServiceTest.php
> Add upload id to rows streamed into BigQuery

- services/analyse/src/Query/CommitTagsQuery.php
- services/analyse/tests/Query/CommitTagsQueryTest.php
> Fix carryforward queries

- services/publish/src/Service/Formatter/PullRequestCommentFormatterService.php
- services/publish/tests/Fixture/PullRequestComment/file-and-tag-pending-uploads.txt
- services/publish/tests/Service/Formatter/PullRequestCommentFormatterServiceTest.php
> Only show pending uploads on pull request when at least one in progress

- services/analyse/src/Query/CommitTagsQuery.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Fix upload query grouping

- services/analyse/src/Query/AbstractLineCoverageQuery.php
- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/src/Query/Trait/ScopeAwareTrait.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
> Fix line coverage query groups

- services/analyse/src/Query/CommitTagsQuery.php
- services/analyse/src/Query/TotalCoverageQuery.php
- services/analyse/src/Query/Trait/CarryforwardAwareTrait.php
- services/analyse/tests/Query/CommitTagsQueryTest.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
> Tidy up and simplify queries

- services/analyse/src/Enum/QueryParameter.php
- services/analyse/src/Handler/EventHandler.php
- services/analyse/src/Model/CachingPublishableCoverageData.php
- services/analyse/src/Model/PublishableCoverageData.php
- services/analyse/src/Model/PublishableCoverageDataInterface.php
- services/analyse/src/Query/AbstractLineCoverageQuery.php
- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/src/Query/Result/TotalUploadsQueryResult.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/src/Query/Trait/ScopeAwareTrait.php
- services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
- services/analyse/tests/Service/QueryServiceTest.php
> Remove the runtime line filtering and replace with application code for filtering to successful uploads

- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Correctly categorise uploads as pending

- services/publish/src/Service/Formatter/PullRequestCommentFormatterService.php
- services/publish/tests/Fixture/PullRequestComment/file-and-tag-pending-uploads.txt
- services/publish/tests/Fixture/PullRequestComment/file-and-tag.txt
> Reformat the comment last update time

- packages/models/src/Model/PublishableMessage/PublishableMessageCollection.php
- services/analyse/src/Handler/EventHandler.php
- services/analyse/src/Model/CachingPublishableCoverageData.php
- services/analyse/src/Model/PublishableCoverageData.php
- services/analyse/src/Model/PublishableCoverageDataInterface.php
- services/analyse/src/Query/Result/TotalUploadsQueryResult.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Handler/EventHandlerTest.php
- services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Use the time of the last uploaded coverage as the message validity

- services/analyse/src/Query/CommitSuccessfulTagsQuery.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/tests/Query/CommitSuccessfulTagsQueryTest.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Update queries to no longer filter out pending uploads and parse date time incorrectly

- .github/workflows/api.yml
> Deploy service with webhook secret

- services/api/src/Controller/WebhookController.php
- services/api/src/Service/AuthTokenService.php
- services/api/tests/Controller/WebhookControllerTest.php
> Fix webhook signature validation for github events

- services/api/src/Service/AuthTokenService.php
> Trim algorithm from beginning of signature

- services/api/src/Service/Webhook/WebhookProcessor.php
> Fix typo in autowire name

- services/api/src/Service/Webhook/PipelineStateChangeWebhookProcessor.php
- services/api/src/Service/Webhook/WebhookProcessor.php
- services/api/src/Service/Webhook/WebhookProcessorInterface.php
> Fix static method

- services/api/src/Controller/WebhookController.php
- services/api/src/Service/AuthTokenService.php
- services/api/tests/Controller/WebhookControllerTest.php
> Improve the signature validation of webhook payloads

- services/api/src/Controller/WebhookController.php
- services/api/src/Service/AuthTokenService.php
- services/api/tests/Controller/WebhookControllerTest.php
> Additional logging for webhooks received

- services/api/src/Service/AuthTokenService.php
> Improve the signature splitting from request

- services/api/src/Controller/WebhookController.php
- services/api/src/Model/Webhook/Github/AbstractGithubWebhook.php
- services/api/src/Service/AuthTokenService.php
- services/api/src/Service/WebhookSignatureService.php
- services/api/tests/Controller/WebhookControllerTest.php
- services/api/tests/Service/WebhookSignatureServiceTest.php
> Improve webhook ingestion testing

- services/analyse/src/Handler/EventHandler.php
> Implement the service subscriber interface

- services/api/src/Enum/JobState.php
- services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
- services/api/src/Model/Webhook/Github/PipelineStateChangeWebhookInterface.php
- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
> Monitor job suite state on received webhooks

- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
> Update query validation

- services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
- services/analyse/src/Service/Event/PipelineCompleteEventProcessor.php
- services/analyse/tests/Client/SqsMessageClientTest.php
- services/analyse/tests/Handler/EventHandlerTest.php
- services/analyse/tests/Service/Event/IngestSuccessEventProcessorTest.php
- services/analyse/tests/Service/Event/PipelineCompleteEventProcessorTest.php
- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
- services/api/tests/Service/Webhook/JobStateChangeWebhookProcessorTest.php
> Add additional tests

- services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
- services/analyse/src/Service/Event/PipelineCompleteEventProcessor.php
- services/analyse/tests/Service/Event/IngestSuccessEventProcessorTest.php
- services/analyse/tests/Service/Event/PipelineCompleteEventProcessorTest.php
> Fix event deserialization error

- services/api/src/Model/SigningParameters.php
> Handle integer pull request ids

- services/publish/src/Kernel.php
> Use Bref kernel for publish service

- infrastructure/outputs.tf
- infrastructure/queue/main.tf
- infrastructure/queue/outputs.tf
> [Part 1] Add FIFO queue for webhooks ingestion

- .github/workflows/infrastructure.yml
> Ensure infra deployments auto approve changes on merge

- .github/workflows/infrastructure.yml
> Run the apply action rather than plan on infra deployments

- services/api/src/Controller/WebhookController.php
> Additional controller logging

- services/api/src/Controller/WebhookController.php
> Fix linting

- services/api/infrastructure/webhook_handler/main.tf
> Apply Webhook queue URL variable

- services/api/infrastructure/api/main.tf
- services/api/infrastructure/webhook_handler/main.tf
> Apply the queue url variable to the right service

- services/api/infrastructure/api/main.tf
> Allow api to push sqs messages to queue

- services/api/infrastructure/api/main.tf
- services/api/infrastructure/webhook_handler/main.tf
> Give webhook handler event bus permissions

- services/analyse/src/Handler/EventHandler.php
- services/analyse/tests/Handler/EventHandlerTest.php
> Ensure processor is injected into container

- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
> Remove unnessesary completed date from in progress annotations

- packages/models/src/Enum/EventType.php
- packages/models/src/Model/Event/EventInterface.php
> Ensure mapping is correct for event discriminator

- services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
> Cast the app id to a string for comparisons

- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
- services/publish/src/Service/Formatter/CheckRunFormatterService.php
- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
- services/publish/tests/Service/Formatter/CheckRunFormatterServiceTest.php
> Fix final check run finish state change

- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Handle null case for uploads query

- services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
- services/analyse/tests/Service/Event/IngestSuccessEventProcessorTest.php
> Remove check run update during uploads

- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
> Add correct interface to publisher

- services/api/src/Handler/WebhookHandler.php
- services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
- services/api/src/Service/Webhook/WebhookProcessor.php
- services/api/src/Service/Webhook/WebhookProcessorInterface.php
- services/api/tests/Service/Webhook/JobStateChangeWebhookProcessorTest.php
- services/api/tests/Service/Webhook/WebhookProcessorTest.php
> Only consider webhooks finished on last record

- infrastructure/warehouse/main.tf
> Switch bucket region and add lifecycle

- services/ingest/src/Service/Persist/GcsPersistService.php
- services/ingest/src/Service/Persist/S3PersistService.php
> Remove close buffer

- packages/models/src/Model/Event/JobStateChange.php
- services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
> Update state change model

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Use commit for checking check run state

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Authenticate as repo owner before querying check runs

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Fix the status validation

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Use correct path

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
- services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
> Exclude self published check runs

- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
> Deduplicate check run annotations when publishing

- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
> Use correct path for annotation count information

- services/ingest/src/Handler/EventHandler.php
- services/ingest/tests/Handler/EventHandlerTest.php
> Only persist coverage when it includes at least one file

- packages/clients/src/Client/Github/GithubAppInstallationClient.php
- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
> Handle multiple pages of check annotations

- infrastructure/warehouse/main.tf
> Set clustering on warehouse line coverage dataset

- infrastructure/warehouse/main.tf
- infrastructure/warehouse/outputs.tf
> [Part 1] Add dedicated table for uploads

- infrastructure/outputs.tf
> Allow upload table as output for remote state

- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Fix incorrect grouping on upload query

- infrastructure/warehouse/main.tf
- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/src/Query/FileCoverageQuery.php
- services/analyse/src/Query/LineCoverageQuery.php
- services/analyse/src/Query/TotalCoverageQuery.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/src/Query/Trait/CarryforwardAwareTrait.php
- services/analyse/src/Query/Trait/DiffAwareTrait.php
- services/analyse/src/Query/Trait/ScopeAwareTrait.php
- services/analyse/tests/Client/BigQueryClientTest.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/ingest/tests/Client/BigQueryClientTest.php
> [Part 4] Move coverage queries to use uploads table

- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
> Fix bug in SQL composition

- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Fix uploads for commit sql grouping

- services/publish/src/Service/Formatter/PullRequestCommentFormatterService.php
- services/publish/src/Service/Publisher/Github/GithubPullRequestCommentPublisherService.php
- services/publish/tests/Fixture/PullRequestComment/file-and-tag-pending-uploads.txt
- services/publish/tests/Fixture/PullRequestComment/file-and-tag.txt
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
> Allow publisher to accept any event interface

- infrastructure/warehouse/main.tf
> Cluster line coverage on file name

- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Handle no uploads on commit

- infrastructure/queue/main.tf
- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Reduce overlapping PR posts from new jobs being added

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Fix ignoring own check runs

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Additional logging

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Use commit sha when getting check runs

- packages/models/src/Model/Event/JobStateChange.php
- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
> Ignore data type for external id

- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
> Filter out job state changes where the state didnt change

- packages/models/src/Enum/EventBus/CoverageEvent.php
- packages/models/src/Model/Event/CoverageFinalised.php
- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
- services/analyse/tests/Service/EventBridgeEventServiceTest.php
- services/api/src/Handler/EventHandler.php
- services/api/src/Service/Event/EventProcessor.php
- services/api/src/Service/Event/EventProcessorInterface.php
- services/api/src/Service/Event/NewCoverageFinalisedEventProcessor.php
- services/api/tests/Command/InvokeEventCommandTest.php
- services/api/tests/Handler/EventHandlerTest.php
- services/api/tests/Service/Event/EventProcessorTest.php
- services/api/tests/Service/Event/NewCoverageFinalisedEventProcessorTest.php
> Refactor the API event processor

- services/api/infrastructure/event_listener/main.tf
> Listen for coverage finalised event

- infrastructure/queue/main.tf
> Switch to long polling queues

- services/analyse/.env
- services/analyse/.env.dev
- services/analyse/infrastructure/analyse/main.tf
- services/analyse/infrastructure/analyse/variables.tf
- services/analyse/infrastructure/main.tf
- services/analyse/infrastructure/query_cache/main.tf
- services/analyse/infrastructure/query_cache/outputs.tf
- services/analyse/infrastructure/query_cache/variables.tf
> Add query cache dynamodb table

- services/analyse/composer.json
- services/analyse/composer.lock
- services/analyse/src/Client/DynamoDbClient.php
- services/analyse/src/Enum/EnvironmentVariable.php
- services/analyse/src/Enum/QueryParameter.php
- services/analyse/src/Model/PublishableCoverageData.php
- services/analyse/src/Model/QueryParameterBag.php
- services/analyse/src/Query/CommitSuccessfulTagsQuery.php
- services/analyse/src/Query/Result/QueryResultInterface.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/src/Service/CachingQueryService.php
- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/src/Service/CoverageAnalyserService.php
- services/analyse/src/Service/QueryService.php
- services/analyse/src/Service/QueryServiceInterface.php
- services/analyse/tests/Client/DynamoDbClientTest.php
- services/analyse/tests/Service/CachingQueryServiceTest.php
- services/analyse/tests/Service/QueryServiceTest.php
> [Part 2] Use query cache as data store

- services/analyse/src/Query/Result/CommitCollectionQueryResult.php
- services/analyse/src/Query/Result/CommitQueryResult.php
- services/analyse/src/Query/Result/CoverageQueryResult.php
- services/analyse/src/Query/Result/FileCoverageCollectionQueryResult.php
- services/analyse/src/Query/Result/FileCoverageQueryResult.php
- services/analyse/src/Query/Result/LineCoverageCollectionQueryResult.php
- services/analyse/src/Query/Result/TagCoverageCollectionQueryResult.php
- services/analyse/src/Query/Result/TagCoverageQueryResult.php
- services/analyse/src/Query/Result/TotalUploadsQueryResult.php
- services/analyse/src/Service/CachingQueryService.php
> Use query cache

- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/src/Query/CommitSuccessfulTagsQuery.php
- services/analyse/src/Query/QueryInterface.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/src/Service/CachingQueryService.php
- services/analyse/src/Service/QueryService.php
- services/analyse/tests/Service/CachingQueryServiceTest.php
> Add conditional caching support for queries which need to be short lived

- services/analyse/src/Enum/QueryParameter.php
- services/analyse/src/Service/CachingQueryService.php
- services/analyse/src/Service/QueryBuilderService.php
- services/analyse/tests/Query/AbstractQueryTestCase.php
- services/analyse/tests/Service/CachingQueryServiceTest.php
- services/analyse/tests/Service/QueryBuilderServiceTest.php
> Ensure query hashes are predictable regardless of parameter order

- services/analyse/tests/Service/QueryBuilderServiceTest.php
> Add additional tests for predictable hashes

- infrastructure/bucket/main.tf
> Delete older outputted coverage models to save space

- services/analyse/src/Client/DynamoDbClient.php
- services/analyse/tests/Client/DynamoDbClientTest.php
> Fix ttl attribute mismatch on query cache

- services/analyse/infrastructure/query_cache/main.tf
> Enable delete protection for query cache

- services/analyse/src/Enum/QueryResult.php
- services/analyse/src/Query/Result/QueryResultInterface.php
> Preserve memory by using enums for discrimination of query results as opposed to the FQCN

- services/analyse/src/Query/Result/FileCoverageQueryResult.php
- services/analyse/src/Query/Result/TagCoverageQueryResult.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
> Tidy up discriminators and fix datetime conversion

- services/analyse/src/Query/CommitSuccessfulTagsQuery.php
- services/analyse/src/Query/FileCoverageQuery.php
- services/analyse/src/Query/LineCoverageQuery.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
> Resolve queries using item iterators

- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
> Ensure alias is correct on tag query

- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
> Rename alias for group by

- services/analyse/src/Query/Result/FileCoverageQueryResult.php
- services/analyse/src/Query/Result/QueryResultInterface.php
- services/analyse/src/Query/Result/TagCoverageQueryResult.php
> Fix deserialization for individual coverage objects which inherit a base class in the discriminator map

- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
- services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
> Use serializer for job state change publishable messages

- services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
- services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
> Increase carryforward history to 200 previous commits

- services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
- services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
> Add additional logging for history fetching

- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
> Fix tag name comparison for existing tags which don't need carrying forward

- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/tests/Query/TagAvailabilityQueryTest.php
> Remove commit scope from tag availability query

- services/analyse/src/Model/PublishableCoverageData.php
> No longer include carried forward coverage in diff-specific coverage calculations

- packages/models/src/Model/Event/JobStateChange.php
- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
- services/analyse/tests/Handler/EventHandlerTest.php
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
- services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
- services/api/tests/Client/EventBridgeEventClientTest.php
> Include job suite state in job handling and add additional tests

- infrastructure/queue/main.tf
- services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
- services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
> Remove delay on webhook handling to see if that improves premature analysis

- services/api/config/migrations/Version20231101210403.php
> Add index on project and commit to optimise job lookups

- services/ingest/src/Service/Persist/GcsPersistService.php
- services/ingest/tests/Service/Persist/GcsPersistServiceTest.php
> Fix incorrect error about upload being unsuccessful

- services/api/src/Service/Webhook/WebhookProcessor.php
> Fix missing index method

- services/analyse/src/Handler/EventHandler.php
> Switch to normalizer method in event handler

- services/orchestrator/infrastructure/main.tf
- services/orchestrator/infrastructure/orchestrator/main.tf
- services/orchestrator/infrastructure/orchestrator/variables.tf
> Ensure orchestrator permissions are correct

- services/orchestrator/infrastructure/orchestrator/main.tf
> Add EventBridge target for Orchestrator lambda

- services/orchestrator/infrastructure/main.tf
- services/orchestrator/infrastructure/orchestrator/main.tf
- services/orchestrator/infrastructure/orchestrator/variables.tf
> Ensure event store table name is injected into service in production

- packages/event/src/Enum/Event.php
- packages/event/src/Model/IngestFailure.php
- packages/event/src/Model/IngestStarted.php
- services/ingest/src/Handler/EventHandler.php
- services/ingest/tests/Handler/EventHandlerTest.php
- services/orchestrator/infrastructure/orchestrator/main.tf
- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/IngestStartedEventProcessor.php
- services/orchestrator/src/Model/Ingestion.php
- services/orchestrator/src/Model/Job.php
- services/orchestrator/tests/Event/IngestStartedEventProcessorTest.php
- services/orchestrator/tests/Service/EventStoreServiceTest.php
> Add ingest started event support

- packages/event/src/Model/EventInterface.php
> Add ingest started event into discriminator map

- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
> Include the correct states in orchestrator job match

- services/orchestrator/composer.json
- services/orchestrator/composer.lock
- services/orchestrator/src/Client/DynamoDbClient.php
- services/orchestrator/src/Event/AbstractOrchestratorEventRecorderProcessor.php
- services/orchestrator/src/Model/AbstractOrchestratedEvent.php
- services/orchestrator/src/Model/Ingestion.php
- services/orchestrator/src/Model/Job.php
- services/orchestrator/src/Model/OrchestratedEventInterface.php
> Use a unique repo identifier in event store and handle backoff algorithm for competing state changes

- services/api/src/Handler/EventHandler.php
> Fix badge coverage percentage not updating

- packages/event/src/Model/EventInterface.php
- services/orchestrator/infrastructure/orchestrator/main.tf
> Apply access to index from lambda

- services/analyse/infrastructure/analyse/main.tf
> Subscribe to events for analyse service

- services/analyse/infrastructure/analyse/main.tf
> Use valid event filtering json

- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
> Add backoff algorithm to prevent duplicate uploads finalised events

- services/ingest/src/Handler/EventHandler.php
- services/ingest/tests/Handler/EventHandlerTest.php
- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
> Add additional logging

- services/ingest/src/Handler/EventHandler.php
- services/ingest/tests/Handler/EventHandlerTest.php
> Only trigger ingest start event when persisting non-empty coverage

- packages/event/src/Model/AnalyseFailure.php
- packages/event/src/Model/IngestFailure.php
- packages/event/src/Model/IngestStarted.php
- packages/event/src/Model/IngestSuccess.php
- packages/event/src/Model/Upload.php
- packages/event/tests/Service/EventProcessorServiceTest.php
- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/ingest/src/Handler/EventHandler.php
- services/ingest/src/Service/BigQueryMetadataBuilderService.php
- services/ingest/tests/Service/EventBridgeEventServiceTest.php
- services/ingest/tests/Service/Persist/S3PersistServiceTest.php
- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/AbstractOrchestratorEventRecorderProcessor.php
- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
- services/orchestrator/src/Exception/OutOfOrderEventException.php
- services/orchestrator/src/Model/Ingestion.php
- services/orchestrator/src/Model/Job.php
- services/orchestrator/src/Model/OrchestratedEventInterface.php
- services/orchestrator/tests/Client/DynamoDbClientTest.php
- services/orchestrator/tests/Event/AbstractIngestEventProcessorTestCase.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
- services/orchestrator/tests/Service/EventStoreServiceTest.php
> Add support for dropping out of order events based on event time

- services/orchestrator/src/Enum/OrchestratedEvent.php
- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/AbstractOrchestratorEventRecorderProcessor.php
- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
- services/orchestrator/src/Model/Finalised.php
- services/orchestrator/src/Model/OrchestratedEventInterface.php
- services/orchestrator/src/Service/CachingEventStoreService.php
- services/orchestrator/src/Service/EventStoreService.php
- services/orchestrator/src/Service/EventStoreServiceInterface.php
- services/orchestrator/tests/Event/IngestFailureEventProcessorTest.php
- services/orchestrator/tests/Event/IngestSuccessEventProcessorTest.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
- services/orchestrator/tests/Service/CachingEventStoreServiceTest.php
> Orchestrate finalised state changes in store

- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
> Correct version number for finalised event state

- packages/event/phpunit.xml.dist
- services/orchestrator/phpunit.xml.dist
> Exclude models from coverage in orchestrator and events

- services/analyse/infrastructure/query_cache/main.tf
- services/orchestrator/infrastructure/event_store/main.tf
> Right size the global secondary index rcu/wcu on dynamodb

- services/analyse/infrastructure/analyse/main.tf
- services/api/infrastructure/api/main.tf
- services/api/infrastructure/event_listener/main.tf
- services/api/infrastructure/webhook_handler/main.tf
- services/ingest/infrastructure/ingest/main.tf
- services/orchestrator/infrastructure/orchestrator/main.tf
- services/publish/infrastructure/publish/main.tf
> Enable active tracing for lambda functions

- services/api/public/index.php
> Use the header variables instead of lambda context

- services/analyse/src/Client/SqsMessageClient.php
- services/api/src/Client/SqsMessageClient.php
> Handle not set trace header in sqs client

- services/analyse/src/Client/EventBridgeEventClient.php
- services/api/public/index.php
- services/api/src/Client/EventBridgeEventClient.php
- services/ingest/src/Client/EventBridgeEventClient.php
- services/orchestrator/src/Client/EventBridgeEventClient.php
> Support event bridge fallbacks for trace ids not propagated

- packages/event/src/Handler/TraceContextAwareTrait.php
- services/analyse/src/Service/EnvironmentService.php
- services/api/public/index.php
- services/api/src/Controller/GraphController.php
- services/api/src/Controller/UploadController.php
- services/api/src/Controller/WebhookController.php
- services/api/src/Service/EnvironmentService.php
- services/ingest/src/Service/EnvironmentService.php
- services/orchestrator/src/Service/EnvironmentService.php
- services/publish/src/Service/EnvironmentService.php
> Fix inspecting the trace context using a trait

- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
- services/orchestrator/tests/Event/AbstractIngestEventProcessorTestCase.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
> Fix bad logic around no finalised event or uploads

- services/api/src/Service/UploadSignerService.php
> Fix signing of uploads

- services/api/src/Handler/EventHandler.php
- services/api/src/Handler/WebhookHandler.php
- services/ingest/src/Handler/EventHandler.php
- services/orchestrator/src/Handler/EventHandler.php
> Fix extraction of trace headers

- packages/telemetry/composer.json
- packages/telemetry/composer.lock
- packages/telemetry/src/Enum/Resolution.php
- packages/telemetry/src/Enum/Unit.php
- packages/telemetry/src/Metric/MetricService.php
- packages/telemetry/src/Model/Metric/Dimensions.php
- packages/telemetry/src/Model/Metric/Metadata.php
- packages/telemetry/src/Model/Metric/MetricDefinition.php
- packages/telemetry/src/Model/Metric/MetricDirective.php
- packages/telemetry/src/Model/Metric/RootNode.php
- services/api/composer.json
- services/api/composer.lock
- services/api/config/packages/monolog.yaml
- services/api/config/services.yaml
- services/api/src/Controller/UploadController.php
- services/api/tests/Controller/UploadControllerTest.php
> Trying out a EMF implementation for recording custom metrics

- packages/telemetry/src/Metric/MetricService.php
- services/api/config/packages/monolog.yaml
> Log metrics to stdout instead of stderr

- packages/telemetry/src/Metric/MetricService.php
> Ensure metric is in microsecond timestamp format

- packages/models/src/Model/PublishableMessage/PublishableCheckAnnotationMessage.php
- packages/models/src/Model/PublishableMessage/PublishableCheckRunMessage.php
- packages/models/src/Model/PublishableMessage/PublishableMessageCollection.php
- packages/models/src/Model/PublishableMessage/PublishableMessageInterface.php
- packages/models/src/Model/PublishableMessage/PublishablePullRequestMessage.php
- services/analyse/composer.json
- services/analyse/composer.lock
- services/analyse/config/packages/monolog.yaml
- services/analyse/config/services.yaml
- services/api/config/packages/monolog.yaml
- services/api/tests/Service/UploadSignerServiceTest.php
- services/ingest/composer.json
- services/ingest/composer.lock
- services/ingest/config/packages/monolog.yaml
- services/ingest/config/services.yaml
- services/ingest/src/Handler/EventHandler.php
- services/ingest/src/Service/Persist/GcsPersistService.php
- services/ingest/tests/Handler/EventHandlerTest.php
- services/ingest/tests/Service/Persist/GcsPersistServiceTest.php
- services/orchestrator/composer.json
- services/orchestrator/composer.lock
- services/orchestrator/config/packages/monolog.yaml
- services/orchestrator/config/services.yaml
- services/publish/composer.json
- services/publish/composer.lock
- services/publish/config/packages/monolog.yaml
- services/publish/config/services.yaml
- services/publish/src/Service/Publisher/MessagePublisherService.php
- services/publish/tests/Service/Publisher/CoveragePublisherServiceTest.php
> Additional metric instrumentation

- services/analyse/config/packages/monolog.yaml
- services/api/config/packages/monolog.yaml
- services/ingest/config/packages/monolog.yaml
- services/orchestrator/config/packages/monolog.yaml
- services/publish/config/packages/monolog.yaml
> Make sure all log lines are terminated with a new line

- services/analyse/src/Handler/EventHandler.php
- services/api/src/Handler/EventHandler.php
- services/orchestrator/src/Handler/EventHandler.php
> Fix event interface on event processor

- packages/telemetry/src/Service/MetricService.php
> Fix the function name dimension

- services/analyse/src/Model/PublishableCoverageData.php
- services/analyse/src/Service/Diff/Github/GithubDiffParserService.php
- services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
- services/analyse/tests/Service/Diff/Github/GithubDiffParserServiceTest.php
> Fix empty commit diff comparison

- .github/workflows/telemetry.yml
- packages/telemetry/composer.json
- packages/telemetry/composer.lock
- packages/telemetry/phpunit.xml.dist
- packages/telemetry/src/Service/MetricService.php
- packages/telemetry/tests/Mock/Factory/MockEnvironmentServiceFactory.php
- packages/telemetry/tests/Service/MetricServiceTest.php
- packages/telemetry/tests/Service/cloudwatch-emf-schema.json
- packages/telemetry/tests/TraceContextTest.php
> Telemetry package tests

- .github/workflows/telemetry.yml
> Capitalise telemetry tests workflow job name

- .github/dependabot.yml
> Add telemetry package to dependabot

- services/analyse/config/packages/sentry.yaml
- services/api/config/packages/sentry.yaml
- services/ingest/config/packages/sentry.yaml
- services/orchestrator/config/packages/sentry.yaml
- services/publish/config/packages/sentry.yaml
> Fixing configuration

- services/api/composer.json
- services/api/composer.lock
> Downgrade API Composer php version 

- services/orchestrator/src/Client/DynamoDbClient.php
- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/AbstractOrchestratorEventRecorderProcessor.php
- services/orchestrator/src/Event/Backoff/BackoffStrategyInterface.php
- services/orchestrator/src/Event/Backoff/EventStoreRecorderBackoffStrategy.php
- services/orchestrator/src/Event/Backoff/ReadyToFinaliseBackoffStrategy.php
- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
- services/orchestrator/src/Exception/EventStoreException.php
- services/orchestrator/src/Model/EventStateChange.php
- services/orchestrator/src/Service/CachingEventStoreService.php
- services/orchestrator/src/Service/EventStoreService.php
- services/orchestrator/src/Service/EventStoreServiceInterface.php
- services/orchestrator/tests/Client/DynamoDbClientTest.php
- services/orchestrator/tests/Event/AbstractIngestEventProcessorTestCase.php
- services/orchestrator/tests/Event/IngestFailureEventProcessorTest.php
- services/orchestrator/tests/Event/IngestSuccessEventProcessorTest.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
- services/orchestrator/tests/Mock/FakeEventStoreRecorderBackoffStrategy.php
- services/orchestrator/tests/Mock/FakeReadyToFinaliseBackoffStrategy.php
- services/orchestrator/tests/Service/CachingEventStoreServiceTest.php
- services/orchestrator/tests/Service/EventStoreServiceTest.php
> Vastly improve the orchestrator tests

- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
> Fix autowire attribute

- packages/clients/src/Client/Github/GithubAppClient.php
- packages/clients/tests/Client/Github/GithubAppClientTest.php
- packages/clients/tests/Client/Github/GithubAppInstallationClientTest.php
> Add additional client tests

- packages/message/src/PublishableMessage/PublishablePullRequestMessage.php
- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/analyse/tests/Client/SqsMessageClientTest.php
- services/publish/src/Command/InvokeCommand.php
- services/publish/tests/Service/Formatter/PullRequestCommentFormatterServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubPullRequestCommentPublisherServiceTest.php
> Remove all old pending uploads behaviour

- services/analyse/src/Service/CachingQueryService.php
- services/analyse/tests/Service/CachingQueryServiceTest.php
> Add cache hit and miss metrics for query caching

- packages/event/src/Model/JobStateChange.php
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
- services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
- services/api/src/Model/Webhook/PipelineStateChangeWebhookInterface.php
- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
- services/api/tests/Client/EventBridgeEventClientTest.php
- services/api/tests/Handler/WebhookHandlerTest.php
- services/api/tests/Service/Webhook/JobStateChangeWebhookProcessorTest.php
- services/orchestrator/src/Command/InvokeCommand.php
- services/orchestrator/tests/Event/AbstractIngestEventProcessorTestCase.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
> Remove old job state change behaviour

- .github/workflows/api.yml
> Fix wrong mapping for sentry DSN during API builds

- packages/message/src/PublishableMessage/PublishablePullRequestMessage.php
- services/analyse/src/Model/CachingPublishableCoverageData.php
- services/analyse/src/Model/PublishableCoverageData.php
- services/analyse/src/Model/PublishableCoverageDataInterface.php
- services/analyse/src/Service/CoverageAnalyserService.php
- services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
- services/publish/src/Service/Formatter/PullRequestCommentFormatterService.php
- services/publish/tests/Fixture/PullRequestComment/empty-diff-coverage.txt
- services/publish/tests/Fixture/PullRequestComment/pr-comment-with-no-pr.txt
- services/publish/tests/Service/Formatter/PullRequestCommentFormatterServiceTest.php
> Handle PR comments where the PRs diff does not contain any lines which were included in the coverage reports

- services/api/src/Controller/UploadController.php
- services/ingest/src/Handler/EventHandler.php
- services/ingest/src/Service/Persist/GcsPersistService.php
- services/publish/src/Service/Publisher/MessagePublisherService.php
> Standardising custom metric names pushed to CloudWatch

- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
> Add an error to catch occasions where the coverage has been finalised eagerly

- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
> Order PR comment tag list by tag name

- packages/models/src/Model/Tag.php
- services/orchestrator/src/Client/DynamoDbClient.php
- services/orchestrator/src/Event/Backoff/EventStoreRecorderBackoffStrategy.php
- services/orchestrator/src/Event/Backoff/ReadyToFinaliseBackoffStrategy.php
- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
> Make the backoff algorithms more responsive and tidy up models

- services/api/src/Kernel.php
> Make the twig cache writable at runtime

- services/api/docker-compose.yml
- services/api/infrastructure/api/main.tf
- services/api/php/conf.dev.d/php.ini
- services/api/rector.php
> Tidy up after API version bump

- services/api/templates/badges/badge.svg.twig
> Remove white space from badge svg

- services/api/templates/badges/badge.svg.twig
> Add back xml namespace to badge svg

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/ingest.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
> Try authoritative classmap generation during builds

- services/api/composer.json
- services/api/composer.lock
- services/api/tests/Service/BadgeServiceTest.php
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 1 with icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 1 without icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 100 with icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 100 without icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 34.64 with icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 34.64 without icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 99 with icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 99 without icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set null with icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set null without icons__1.xml
> Add snapshot tests for badge generation

- .github/workflows/release-drafter.yml
> Add concurrency group to release drafter workflow

- packages/telemetry/composer.json
- packages/telemetry/composer.lock
- packages/telemetry/src/Service/SymfonySerializerLineFormatter.php
- services/analyse/config/packages/monolog.yaml
- services/api/config/packages/monolog.yaml
- services/api/src/Controller/UploadController.php
- services/api/src/Model/UploadError.php
- services/api/tests/Controller/UploadControllerTest.php
- services/ingest/config/packages/monolog.yaml
- services/orchestrator/config/packages/monolog.yaml
- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/AbstractOrchestratorEventRecorderProcessor.php
- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
- services/orchestrator/src/Model/EventStateChangeCollection.php
- services/orchestrator/src/Service/EventStoreService.php
- services/publish/config/packages/monolog.yaml
> Replace native PHP JSON log serialization with Symfony Serializer

- packages/telemetry/src/Service/SymfonySerializerLineFormatter.php
- services/analyse/src/Model/QueryParameterBag.php
> Fix logging of WeakMap firing exceptions

- packages/contracts/src/PublishableMessage/PublishableMessage.php
- packages/message/src/PublishableMessage/PublishableAnnotationInterface.php
- packages/message/src/PublishableMessage/PublishableCheckRunMessage.php
- packages/message/src/PublishableMessage/PublishableMessageCollection.php
- packages/message/src/PublishableMessage/PublishableMessageInterface.php
- packages/message/src/PublishableMessage/PublishableMissingCoverageAnnotationMessage.php
- packages/message/src/PublishableMessage/PublishablePartialBranchAnnotationMessage.php
- packages/message/src/PublishableMessage/PublishablePullRequestMessage.php
- services/analyse/src/Query/AbstractLineCoverageQuery.php
- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/src/Query/Result/LineCoverageQueryResult.php
- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/analyse/src/Service/LineGroupingService.php
- services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/analyse/tests/Service/Event/UploadsFinalisedEventProcessorTest.php
- services/analyse/tests/Service/LineGroupingServiceTest.php
- services/analyse/tests/Service/QueryServiceTest.php
- services/publish/src/Command/InvokeCommand.php
- services/publish/src/Service/Formatter/CheckAnnotationFormatterService.php
- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
- services/publish/tests/Handler/EventHandlerTest.php
- services/publish/tests/Service/Formatter/CheckAnnotationFormatterServiceTest.php
- services/publish/tests/Service/Publisher/CoveragePublisherServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
> [Part 1] Smarter line annotations on PRs

- packages/message/src/PublishableMessage/PublishableAnnotationInterface.php
> Fix discriminator map for annotation interface

- services/analyse/src/Query/Result/LineCoverageQueryResult.php
> Resolve serialization of line type booleans

- packages/message/src/PublishableMessage/PublishableMissingCoverageAnnotationMessage.php
> Resolve serialization of annotation placement boolean

- services/analyse/src/Query/LineCoverageQuery.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
> Re-order line results from data warehouse

- services/api/src/Service/BadgeService.php
- services/api/tests/Service/BadgeServiceTest.php
> Make sure to show badges with two decimal places

- packages/message/src/PublishableMessage/PublishablePartialBranchAnnotationMessage.php
> Resolve the serialized name for branch annotation messages

- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
> Move placement of annotations in GitHub

- services/analyse/src/Model/PublishableCoverageData.php
- services/analyse/src/Model/PublishableCoverageDataInterface.php
- services/analyse/src/Service/Diff/CachingDiffParserService.php
- services/analyse/src/Service/Diff/DiffParserServiceInterface.php
- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/analyse/src/Service/LineGroupingService.php
- services/analyse/tests/Service/Event/UploadsFinalisedEventProcessorTest.php
- services/analyse/tests/Service/LineGroupingServiceTest.php
- services/publish/src/Service/Formatter/CheckAnnotationFormatterService.php
- services/publish/tests/Service/Formatter/CheckAnnotationFormatterServiceTest.php
> [Part 2] Include diff context in annotations

- services/analyse/src/Service/LineGroupingService.php
- services/analyse/tests/Service/LineGroupingServiceTest.php
> Handle overlapping partial branch annotations and missing coverage

- services/analyse/src/Service/LineGroupingService.php
- services/analyse/tests/Service/LineGroupingServiceTest.php
- services/publish/src/Service/Formatter/CheckAnnotationFormatterService.php
> Refactor and simplify the line annotation behaviour

- services/analyse/src/Model/PublishableCoverageDataInterface.php
- services/analyse/src/Service/Diff/CachingDiffParserService.php
- services/analyse/src/Service/Diff/DiffParserServiceInterface.php
- services/analyse/src/Service/LineGroupingService.php
- services/analyse/tests/Service/LineGroupingServiceTest.php
> Improve the handling of non-sequential diffs when grouping annotations

- packages/event/src/Model/Upload.php
- packages/event/tests/Service/EventProcessorServiceTest.php
- services/analyse/src/Command/InvokeCommand.php
- services/analyse/tests/Client/SqsMessageClientTest.php
- services/analyse/tests/Query/AbstractQueryTestCase.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TagAvailabilityQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
- services/analyse/tests/Service/Diff/DiffParserServiceTest.php
- services/analyse/tests/Service/History/CommitHistoryServiceTest.php
- services/analyse/tests/Service/QueryBuilderServiceTest.php
- services/api/src/Model/SigningParameters.php
- services/api/tests/Controller/UploadControllerTest.php
- services/api/tests/Model/SigningParametersTest.php
- services/api/tests/Service/UploadServiceTest.php
- services/ingest/src/Handler/EventHandler.php
- services/ingest/tests/Client/EventBridgeEventClientTest.php
- services/ingest/tests/Service/BigQueryMetadataBuilderServiceTest.php
- services/ingest/tests/Service/Persist/GcsPersistServiceTest.php
- services/ingest/tests/Service/Persist/S3PersistServiceTest.php
- services/orchestrator/tests/Event/AbstractIngestEventProcessorTestCase.php
- services/orchestrator/tests/Event/IngestFailureEventProcessorTest.php
- services/orchestrator/tests/Event/IngestSuccessEventProcessorTest.php
- services/publish/src/Command/InvokeCommand.php
- services/publish/tests/Service/Formatter/PullRequestCommentFormatterServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubPullRequestCommentPublisherServiceTest.php
> Capture the base commit and base ref from signed parameters

- services/analyse/tests/Service/Event/UploadsFinalisedEventProcessorTest.php
- services/publish/src/Service/Formatter/CheckRunFormatterService.php
- services/publish/src/Service/Formatter/PullRequestCommentFormatterService.php
- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
- services/publish/tests/Fixture/PullRequestComment/coverage-drop.txt
- services/publish/tests/Fixture/PullRequestComment/empty-diff-coverage.txt
- services/publish/tests/Fixture/PullRequestComment/file-and-tag.txt
- services/publish/tests/Fixture/PullRequestComment/pr-comment-with-no-pr.txt
- services/publish/tests/Service/Formatter/CheckRunFormatterServiceTest.php
- services/publish/tests/Service/Formatter/PullRequestCommentFormatterServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
> [Part 4] First pass at surfacing coverage comparison metics

- services/analyse/src/Model/ReportWaypoint.php
- services/analyse/src/Service/CoverageAnalyserService.php
- services/analyse/src/Service/Diff/CachingDiffParserService.php
- services/analyse/src/Service/Diff/DiffParserService.php
- services/analyse/src/Service/Diff/DiffParserServiceInterface.php
- services/analyse/src/Service/Diff/Github/GithubDiffParserService.php
- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/analyse/tests/Model/ReportWaypointTest.php
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
- services/analyse/tests/Service/CoverageAnalyserServiceTest.php
- services/analyse/tests/Service/Diff/CachingDiffParserServiceTest.php
- services/analyse/tests/Service/Diff/DiffParserServiceTest.php
- services/analyse/tests/Service/Diff/Github/GithubDiffParserServiceTest.php
- services/analyse/tests/Service/QueryBuilderServiceTest.php
> Resolve diff comparison not using PR diff

- services/analyse/src/Model/Report.php
- services/analyse/src/Service/CachingCoverageAnalyserService.php
- services/analyse/src/Service/CoverageAnalyserService.php
- services/analyse/src/Service/CoverageAnalyserServiceInterface.php
- services/analyse/src/Service/QueryServiceInterface.php
- services/analyse/tests/Model/ReportTest.php
- services/analyse/tests/Service/CachingCoverageAnalyserServiceTest.php
- services/analyse/tests/Service/CoverageAnalyserServiceTest.php
> Lazy load and more heavily cache report metrics

- services/analyse/src/Service/CachingCoverageAnalyserService.php
> Handle caching null diff coverage percentages

- services/analyse/src/Service/CachingCoverageAnalyserService.php
> Handle not reindexing keys for least covered diff files

- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
> Fix ref and commit being wrong in uploads finalised event

- services/analyse/src/Model/ReportComparison.php
- services/analyse/tests/Model/ReportComparisonTest.php
> Round report comparison change percentages to 2 decimal places

- services/analyse/src/Query/AbstractLineCoverageQuery.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/src/Service/LineGroupingService.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/analyse/tests/Service/LineGroupingServiceTest.php
> Fix issue with branches being reported on PRs as none missing

- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
> Include line bools in tag coverage queries

- services/analyse/src/Service/History/CommitHistoryService.php
- services/analyse/src/Service/History/CommitHistoryServiceInterface.php
- services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
> Fix service interface

- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/analyse/tests/Service/Event/UploadsFinalisedEventProcessorTest.php
> [Part 6] Use parent commits as fallback comparison

- packages/message/src/PublishableMessage/PublishableCheckRunMessage.php
- packages/message/src/PublishableMessage/PublishablePullRequestMessage.php
- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/analyse/src/Service/Event/UploadsStartedEventProcessor.php
- services/analyse/tests/Client/SqsMessageClientTest.php
- services/publish/src/Command/InvokeCommand.php
- services/publish/src/Service/Formatter/CheckRunFormatterService.php
- services/publish/src/Service/Formatter/PullRequestCommentFormatterService.php
- services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
- services/publish/tests/Service/Formatter/CheckRunFormatterServiceTest.php
- services/publish/tests/Service/Formatter/PullRequestCommentFormatterServiceTest.php
- services/publish/tests/Service/Formatter/__snapshots__/PullRequestCommentFormatterServiceTest__testFormat with data set 0__1.txt
- services/publish/tests/Service/Formatter/__snapshots__/PullRequestCommentFormatterServiceTest__testFormat with data set 1__1.txt
- services/publish/tests/Service/Formatter/__snapshots__/PullRequestCommentFormatterServiceTest__testFormat with data set 2__1.txt
- services/publish/tests/Service/Formatter/__snapshots__/PullRequestCommentFormatterServiceTest__testFormat with data set 3__1.txt
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubPullRequestCommentPublisherServiceTest.php
> Fix the base of comparisons being reported as PR base rather than the base report used

- services/analyse/infrastructure/analyse/main.tf
> Increase analyse service timeout

- services/analyse/src/Service/History/CachingCommitHistoryService.php
- services/analyse/tests/Service/History/CachingCommitHistoryServiceTest.php
> Make sure cached commit history doesnt include waypoint commit as first preceding

- services/api/src/Handler/WebhookHandler.php
- services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
- services/api/src/Model/Webhook/PipelineStateChangeWebhookInterface.php
- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
- services/api/tests/Handler/WebhookHandlerTest.php
> Handle empty parent commits in webhooks from GitHub

- packages/configuration/composer.json
- packages/configuration/composer.lock
- packages/configuration/src/Constant/Configuration.php
- packages/contracts/src/Event/Event.php
- packages/event/src/Model/ConfigurationFileChange.php
- services/api/composer.json
- services/api/composer.lock
- services/api/src/Enum/WebhookProcessorEvent.php
- services/api/src/Enum/WebhookType.php
- services/api/src/Model/Webhook/CommitsPushedWebhookInterface.php
- services/api/src/Model/Webhook/Github/GithubPushWebhook.php
- services/api/src/Model/Webhook/Github/GithubPushedCommit.php
- services/api/src/Model/Webhook/PushedCommitInterface.php
- services/api/src/Model/Webhook/WebhookInterface.php
- services/api/src/Service/Webhook/CommitsPushedWebhookProcessor.php
- services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
- services/api/tests/Controller/WebhookControllerTest.php
- services/api/tests/Fixture/Webhook/github_push.json
- services/api/tests/Service/Webhook/CommitsPushedWebhookProcessorTest.php
- services/api/tests/Service/Webhook/WebhookProcessorTest.php
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 34.6 with icons__1.xml
- services/api/tests/Service/__snapshots__/BadgeServiceTest__testBadgeRendering with data set 34.6 without icons__1.xml
> Support a version controlled configuration format

- infrastructure/configuration/main.tf
- infrastructure/configuration/outputs.tf
- infrastructure/configuration/variables.tf
- infrastructure/main.tf
- infrastructure/outputs.tf
- services/orchestrator/infrastructure/orchestrator/main.tf
> Add DynamoDb table for configuration storage

- services/orchestrator/infrastructure/orchestrator/main.tf
> Add delete item permission to orchestrator

- services/orchestrator/src/Event/ConfigurationFileChangeEventProcessor.php
- services/orchestrator/tests/Event/ConfigurationFileChangeEventProcessorTest.php
> Only commit configuration file changes on main branches

- coveragerobot.yml
> Add config file

- services/api/src/Service/Webhook/CommitsPushedWebhookProcessor.php
> Remove the prefix from ref

- coveragerobot.yml
> Update config file comment

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/ingest.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
> Remove cleanup step and coverage artifact

- packages/configuration/phpunit.xml.dist
- packages/configuration/src/Mock/MockSettingServiceFactory.php
- packages/contracts/src/Event/BaseAwareEventInterface.php
- packages/contracts/src/Event/EventInterface.php
- packages/contracts/src/Event/ParentAwareEventInterface.php
- packages/event/src/Model/AnalyseFailure.php
- packages/event/src/Model/ConfigurationFileChange.php
- packages/event/src/Model/CoverageFinalised.php
- packages/event/src/Model/IngestFailure.php
- packages/event/src/Model/IngestStarted.php
- packages/event/src/Model/IngestSuccess.php
- packages/event/src/Model/JobStateChange.php
- packages/event/src/Model/Upload.php
- packages/event/src/Model/UploadsFinalised.php
- packages/event/src/Model/UploadsStarted.php
- services/analyse/composer.json
- services/analyse/composer.lock
- services/analyse/config/bundles.php
- services/analyse/src/Service/CoverageComparisonService.php
- services/analyse/src/Service/Event/UploadsFinalisedEventProcessor.php
- services/analyse/src/Service/Event/UploadsStartedEventProcessor.php
- services/analyse/symfony.lock
- services/analyse/tests/Service/CoverageComparisonServiceTest.php
- services/analyse/tests/Service/Event/UploadsFinalisedEventProcessorTest.php
> Use setting service to control if line annotations are generated

- services/analyse/infrastructure/analyse/main.tf
> Allow analyse to access configuration

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/ingest.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- rector.php
> Apply Symfony 6.4 rector rules globally

- packages/message/src/Client/PublishClient.php
- packages/message/tests/Client/PublishClientTest.php
- services/api/src/Client/WebhookQueueClient.php
- services/api/tests/Client/WebhookQueueClientTest.php
> Fix queue name error

- services/analyse/infrastructure/analyse/main.tf
- services/api/infrastructure/api/main.tf
> Add permissions to retrieve queue urls

- .github/dependabot.yml
> Add dependabot config for new packages

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/event.yml
- .github/workflows/ingest.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
> Update path triggers for package and service workflows

- services/analyse/composer.json
- services/analyse/composer.lock
- services/analyse/src/Query/FileCoverageQuery.php
- services/analyse/src/Query/LineCoverageQuery.php
- services/analyse/src/Query/Result/CoverageQueryResult.php
- services/analyse/src/Query/Result/FileCoverageCollectionQueryResult.php
- services/analyse/src/Query/Result/FileCoverageQueryResult.php
- services/analyse/src/Query/Result/LineCoverageCollectionQueryResult.php
- services/analyse/src/Query/Result/LineCoverageQueryResult.php
- services/analyse/src/Query/Result/TagAvailabilityCollectionQueryResult.php
- services/analyse/src/Query/Result/TagAvailabilityQueryResult.php
- services/analyse/src/Query/Result/TagCoverageCollectionQueryResult.php
- services/analyse/src/Query/Result/TotalUploadsQueryResult.php
- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/src/Query/TotalCoverageQuery.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/src/Service/QueryService.php
- services/analyse/tests/Service/QueryServiceTest.php
> Validate query results when deserializing

- services/ingest/src/Handler/EventHandler.php
> Default to null if the various optional properties are provided empty

- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/tests/Query/__snapshots__/TagAvailabilityQueryTest__testGetQuery with data set 0__1.txt
> Remove tag availability limit

- services/api/src/Model/Webhook/CommitsPushedWebhookInterface.php
- services/api/tests/Webhook/WebhookValidationServiceTest.php
> Allow no commits in commit push webhooks for deleted refs

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/event.yml
- .github/workflows/ingest.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
> Always send test coverage if available

- infrastructure/warehouse/main.tf
> [Part 1] Add partitioned table for line coverage

- infrastructure/warehouse/main.tf
- infrastructure/warehouse/outputs.tf
> Switch over to the line coverage name for the new partitioned table

- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/__snapshots__/TagAvailabilityQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/TotalUploadsQueryTest__testGetQuery with data set 0__1.txt
> Stringify the ingest times from queries

- services/analyse/src/Query/Trait/ScopeAwareTrait.php
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 3__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 1__1.txt
> Stringify the ingest times into queries

- services/analyse/src/Query/Trait/ScopeAwareTrait.php
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 3__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 1__1.txt
> Use only the date in the ingest scope to prune partitions further

- services/analyse/src/Model/CarryforwardTag.php
- services/analyse/src/Model/QueryParameterBag.php
- services/analyse/src/Model/Report.php
- services/analyse/src/Model/ReportWaypoint.php
- services/analyse/src/Query/Result/TagAvailabilityQueryResult.php
- services/analyse/src/Query/Result/TotalUploadsQueryResult.php
- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/src/Query/Trait/CarryforwardAwareTrait.php
- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/src/Service/CoverageAnalyserService.php
- services/analyse/tests/Model/ReportTest.php
- services/analyse/tests/Model/ReportWaypointTest.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TagAvailabilityQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
- services/analyse/tests/Query/__snapshots__/TagAvailabilityQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/TotalUploadsQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
- services/analyse/tests/Service/QueryBuilderServiceTest.php
> Tidy up models around carrying forward test coverage

- services/analyse/src/Model/QueryParameterBag.php
- services/analyse/tests/Service/CoverageAnalyserServiceTest.php
> Solve garbage collection buffer overflow warning

- services/analyse/src/Model/QueryParameterBag.php
- services/analyse/src/Model/Report.php
- services/analyse/src/Query/Result/TotalUploadsQueryResult.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/src/Service/CoverageAnalyserService.php
- services/analyse/tests/Model/ReportTest.php
- services/analyse/tests/Query/__snapshots__/TotalUploadsQueryTest__testGetQuery with data set 0__1.txt
> Solve infinite query parameter recursion

- services/analyse/src/Model/Report.php
- services/analyse/src/Model/ReportComparison.php
- services/analyse/src/Model/ReportInterface.php
- services/analyse/src/Query/TotalCoverageQuery.php
- services/analyse/tests/Model/ReportComparisonTest.php
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 1__1.txt
> Use unrounded floats when comparing coverage

- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
- services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
> Allow for substitution of base ref when looking up history for deleted refs

- packages/configuration/composer.json
- packages/configuration/composer.lock
- packages/configuration/src/Client/DynamoDbClient.php
- packages/configuration/src/Enum/SettingKey.php
- packages/configuration/src/Enum/SettingValueType.php
- packages/configuration/src/Exception/InvalidSettingValueException.php
- packages/configuration/src/Exception/SettingRetrievalFailedException.php
- packages/configuration/src/Model/PathReplacement.php
- packages/configuration/src/Service/ConfigurationFileService.php
- packages/configuration/src/Service/SettingService.php
- packages/configuration/src/Setting/LineAnnotationSetting.php
- packages/configuration/src/Setting/PathReplacementsSetting.php
- packages/configuration/src/Setting/SettingInterface.php
- packages/configuration/tests/Service/ConfigurationFileServiceTest.php
- packages/configuration/tests/Service/SettingServiceTest.php
- packages/configuration/tests/Setting/LineAnnotationSettingTest.php
- packages/configuration/tests/Setting/PathReplacementsSettingTest.php
> [Part 1] Add path replacement setting support

- services/analyse/src/Service/CoverageComparisonService.php
> Still generate a base comparison for a merged pull request

- packages/configuration/src/Setting/PathReplacementsSetting.php
- packages/configuration/tests/Setting/PathReplacementsSettingTest.php
> Use map for storing path replacement configuration

- packages/configuration/src/Model/PathReplacement.php
> Stop null returns from path replacement after

- packages/configuration/src/Model/PathReplacement.php
- packages/configuration/src/Setting/PathReplacementsSetting.php
- packages/configuration/tests/Setting/PathReplacementsSettingTest.php
> Allow nulls to be stored in path replacement map

- services/ingest/src/Handler/EventHandler.php
- services/ingest/src/Service/CoverageFileParserService.php
- services/ingest/src/Service/PathFixingService.php
- services/ingest/src/Strategy/Clover/CloverParseStrategy.php
- services/ingest/src/Strategy/Lcov/LcovParseStrategy.php
- services/ingest/src/Strategy/ParseStrategyInterface.php
- services/ingest/tests/Fixture/Clover/complex-jest.xml
- services/ingest/tests/Fixture/Clover/complex-php.xml
- services/ingest/tests/Fixture/Lcov/absolute-path-complex.info
- services/ingest/tests/Handler/EventHandlerTest.php
- services/ingest/tests/Service/CoverageFileParserServiceTest.php
- services/ingest/tests/Service/PathFixingServiceTest.php
- services/ingest/tests/Strategy/AbstractParseStrategyTestCase.php
- services/ingest/tests/Strategy/Clover/CloverParseStrategyTest.php
- services/ingest/tests/Strategy/Lcov/LcovParseStrategyTest.php
> [Part 2] Run path replacements when injecting coverage files

- services/ingest/infrastructure/ingest/main.tf
> Allow ingest service access to configuration dynamo table

- services/analyse/src/Service/CoverageAnalyserService.php
> Handle diff coverage data when theres been no uploads

- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/src/Query/Trait/CarryforwardAwareTrait.php
- services/analyse/src/Query/Trait/ScopeAwareTrait.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 3__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 2__1.txt
> Aggregate all ingest time options into one single clause

- packages/configuration/src/Enum/SettingKey.php
- packages/configuration/src/Enum/SettingValueType.php
- packages/configuration/src/Model/DefaultTagBehaviour.php
- packages/configuration/src/Model/IndividualTagBehaviour.php
- packages/configuration/src/Service/ConfigurationFileService.php
- packages/configuration/src/Service/TagBehaviourService.php
- packages/configuration/src/Setting/DefaultTagBehaviourSetting.php
- packages/configuration/src/Setting/IndividualTagBehavioursSetting.php
- packages/configuration/tests/Service/ConfigurationFileServiceTest.php
- packages/configuration/tests/Service/TagBehaviourServiceTest.php
- packages/configuration/tests/Setting/DefaultTagBehaviourSettingTest.php
- packages/configuration/tests/Setting/IndividualTagBehavioursSettingTest.php
- packages/configuration/tests/Setting/LineAnnotationSettingTest.php
> [Part 1] Add settings and wrappers for customising tag behaviour

- packages/configuration/src/Mock/MockTagBehaviourServiceFactory.php
- packages/configuration/src/Setting/DefaultTagBehaviourSetting.php
- packages/configuration/tests/Setting/DefaultTagBehaviourSettingTest.php
- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
> [Part 2] Only carryforward when behaviour setting allows for tag to be carried

- packages/configuration/src/Service/TagBehaviourService.php
- packages/configuration/tests/Service/TagBehaviourServiceTest.php
> Use setting service which caches requests for tag behaviour lookups

- services/orchestrator/infrastructure/orchestrator/main.tf
- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/CoverageFinalisedEventProcessor.php
- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
- services/orchestrator/src/Event/OverallCommitStateAwareTrait.php
- services/orchestrator/src/Model/Finalised.php
- services/orchestrator/tests/Event/CoverageFinalisedEventProcessorTest.php
- services/orchestrator/tests/Service/EventProcessorServiceTest.php
> Listen for coverage finalised events and record current state for finalise events

- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 1__1.txt
> Fix an incorrect alias name

- packages/contracts/src/Event/EventInterface.php
- services/api/src/Model/ParametersInterface.php
- services/api/src/Model/SigningParameters.php
- services/api/src/Model/Webhook/CommitsPushedWebhookInterface.php
- services/api/src/Model/Webhook/PipelineStateChangeWebhookInterface.php
- services/api/src/Model/Webhook/PushedCommitInterface.php
- services/api/src/Model/Webhook/WebhookInterface.php
- services/api/tests/Webhook/WebhookValidationServiceTest.php
> Tighten up signing parameter and webhook constraints

- services/analyse/src/Service/Carryforward/CachingCarryforwardTagService.php
- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/src/Service/Carryforward/CarryforwardTagServiceInterface.php
- services/analyse/src/Service/CoverageAnalyserService.php
> Include carryforward ingest partitions in query

- infrastructure/warehouse/main.tf
> Add total lines as a nullable field recorded on uploads

- services/ingest/src/Service/BigQueryMetadataBuilderService.php
- services/ingest/src/Service/Persist/GcsPersistService.php
> [Part 2] Add total lines as a upload row property

- infrastructure/warehouse/main.tf
- services/ingest/src/Service/BigQueryMetadataBuilderService.php
- services/ingest/src/Service/Persist/GcsPersistService.php
> Add generated time and source format to upload metadata

- services/api/src/Client/WebhookQueueClient.php
> Fix webhook client interface

- services/publish/src/Handler/EventHandler.php
- services/publish/src/Service/MessagePublisherService.php
- services/publish/src/Service/MessagePublisherServiceInterface.php
- services/publish/tests/Handler/EventHandlerTest.php
- services/publish/tests/Service/Publisher/CoveragePublisherServiceTest.php
- services/publish/tests/Service/Publisher/MessagePublisherServiceTest.php
> Fix publisher interfaces

- services/analyse/src/Service/CoverageAnalyserService.php
- services/analyse/src/Service/QueryService.php
> Tidy up constructors

- services/api/src/Entity/Job.php
- services/api/src/Entity/Project.php
> Remove final on entities so they can be lazy loaded

- services/analyse/src/Event/UploadsFinalisedEventProcessor.php
- services/analyse/tests/Event/UploadsFinalisedEventProcessorTest.php
> Dont publish line comment collection when empty

- services/publish/src/Extension/Function/CoverageReportFunction.php
- services/publish/src/Extension/Function/EventFunction.php
- services/publish/templates/check_run/complete_check_run.md.twig
- services/publish/templates/line_comment/line_comment_body.md.twig
- services/publish/templates/pull_request/full_pull_request_comment.md.twig
- services/publish/tests/Service/Templating/TemplateRenderingServiceTest.php
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 10__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 11__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 12__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 13__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 14__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 15__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 16__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 4__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 5__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 6__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 7__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 8__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 9__1.txt
> Include parent commit comparisons in results

- services/publish/templates/check_run/complete_check_run.md.twig
- services/publish/templates/pull_request/full_pull_request_comment.md.twig
> Handle falsey coverage change values

- phpcs.xml
> Remove old exclusions now codesniffer supports php 8.3

- services/publish/templates/check_run/complete_check_run.md.twig
- services/publish/templates/pull_request/full_pull_request_comment.md.twig
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 7__1.txt
> Handle falsey coverage change values in templates

- services/publish/src/Handler/EventHandler.php
> Handle invalid message groups

- packages/clients/composer.json
- packages/clients/composer.lock
- packages/clients/src/Client/Github/GithubAppClient.php
- packages/clients/src/Client/Github/GithubAppInstallationClient.php
- packages/clients/tests/Client/Github/GithubAppClientTest.php
- packages/clients/tests/Client/Github/GithubAppInstallationClientTest.php
- packages/telemetry/src/Service/MetricService.php
- packages/telemetry/src/Service/MetricServiceInterface.php
- packages/telemetry/tests/Service/MetricServiceTest.php
- services/analyse/src/Service/Diff/Github/GithubDiffParserService.php
- services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
- services/analyse/tests/Service/Diff/Github/GithubDiffParserServiceTest.php
- services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
> Metrics on provider api calls

- services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 2__1.txt
> Fix queries missing aggregation for total lines

- services/analyse/src/Event/UploadsFinalisedEventProcessor.php
> Fix report size metric showing incorrectly for report comparisons

- packages/configuration/config/services.yaml
- packages/configuration/src/Service/CachingSettingService.php
- packages/configuration/src/Service/EnvironmentService.php
- packages/configuration/src/Service/SettingService.php
- packages/configuration/src/Service/SettingServiceInterface.php
- packages/configuration/src/Setting/DefaultTagBehaviourSetting.php
- packages/configuration/src/Setting/IndividualTagBehavioursSetting.php
- packages/configuration/src/Setting/LineCommentTypeSetting.php
- packages/configuration/src/Setting/PathReplacementsSetting.php
- packages/configuration/src/Setting/SettingInterface.php
- packages/configuration/tests/Service/CachingSettingServiceTest.php
- packages/configuration/tests/Service/SettingServiceTest.php
- packages/configuration/tests/Setting/DefaultTagBehaviourSettingTest.php
- packages/configuration/tests/Setting/IndividualTagBehavioursSettingTest.php
- packages/configuration/tests/Setting/LineCommentTypeSettingTest.php
- packages/configuration/tests/Setting/PathReplacementsSettingTest.php
> Refactor setting handling to fix path replacement serialization bug

- services/publish/templates/pull_request/full_pull_request_comment.md.twig
- services/publish/tests/Service/Templating/TemplateRenderingServiceTest.php
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 17__1.txt
> Fix falsey comparison on pull request template

- services/api/src/Controller/WebhookController.php
- services/api/src/Service/WebhookSignatureServiceInterface.php
> Silence webhook type error for unsupported webhook types

- services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
- services/api/src/Model/Webhook/Github/GithubPushWebhook.php
- services/api/src/Model/Webhook/WebhookInterface.php
- services/api/src/Webhook/Processor/CommitsPushedWebhookProcessor.php
- services/api/src/Webhook/Processor/JobStateChangeWebhookProcessor.php
- services/api/tests/Handler/WebhookHandlerTest.php
- services/api/tests/Webhook/Processor/JobStateChangeWebhookProcessorTest.php
- services/api/tests/Webhook/Signature/Github/GithubWebhookSignatureServiceTest.php
> Expose event time from webhook payload properties

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/event.yml
- .github/workflows/ingest.yml
- .github/workflows/local.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
> Remove unnecessary configuration arg in phpunit command

- packages/configuration/composer.json
- packages/contracts/composer.json
- packages/event/composer.json
- packages/event/src/Client/EventBusClient.php
- packages/event/src/EventBundle.php
- packages/event/tests/Client/EventBusClientTest.php
- packages/local/composer.json
- packages/message/composer.json
- packages/telemetry/composer.json
- services/orchestrator/composer.lock
> Expose bundle config for extension package

- infrastructure/events/main.tf
> Fix policy syntax

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/event.yml
- .github/workflows/infrastructure.yml
- .github/workflows/ingest.yml
- .github/workflows/local.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
> Add support for merge group tests

- services/publish/src/Service/Publisher/Github/GithubCheckRunAwareTrait.php
> Ensure correct conclusion pushed to GitHub

- services/publish/src/Service/Publisher/Github/GithubCheckRunAwareTrait.php
> Include conclusion in result check run update

- services/publish/src/Extension/Function/CoverageReportFunction.php
- services/publish/templates/coverage/pull_request/full_pull_request_comment.md.twig
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 0__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 17__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 1__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 2__1.txt
> Publish untested line metrics on pull request comments

- services/publish/templates/coverage/pull_request/full_pull_request_comment.md.twig
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 0__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 17__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 1__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 2__1.txt
> Tweak the pull request comment headline

- services/publish/templates/coverage/pull_request/full_pull_request_comment.md.twig
- services/publish/tests/Service/Templating/TemplateRenderingServiceTest.php
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 0__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 17__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 1__1.txt
- services/publish/tests/Service/Templating/__snapshots__/TemplateRenderingServiceTest__testRendering with data set 2__1.txt
> Update markdown styling

- packages/local/config/services.yaml
- packages/local/src/Service/ManualInputEventBuilder.php
> Fix local invoked events not deserializing nested properties correctly

- services/analyse/src/Service/AbstractCoverageAnalyserService.php
- services/analyse/tests/Service/CachingCoverageAnalyserServiceTest.php
> Fix coverage percentage on diff showing 0 instead of null

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/event.yml
- .github/workflows/infrastructure.yml
- .github/workflows/ingest.yml
- .github/workflows/local.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
> Remove the path filters from merge queues

- services/analyse/src/Enum/QueryResult.php
> Remove unused enum cases

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/event.yml
- .github/workflows/infrastructure.yml
- .github/workflows/ingest.yml
- .github/workflows/local.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
> Try fixing the jobs not triggering for merge queue pull requests

- packages/event/config/packages/monolog.yaml
- packages/event/src/EventBundle.php
- packages/telemetry/config/packages/monolog.yaml
- packages/telemetry/config/services.yaml
- packages/telemetry/src/Service/SymfonySerializerLineFormatter.php
- packages/telemetry/src/TelemetryBundle.php
- services/analyse/config/packages/framework.yaml
- services/analyse/config/packages/monolog.yaml
- services/api/config/packages/monolog.yaml
- services/ingest/config/packages/framework.yaml
- services/ingest/config/packages/monolog.yaml
- services/orchestrator/config/packages/monolog.yaml
- services/publish/config/packages/monolog.yaml
> Tidy up monolog config

- services/api/.env.dev
- services/api/.env.test
- services/api/config/packages/async_aws.yaml
> Tidy up api s3 config

- infrastructure/.terraform.lock.hcl
- infrastructure/authentication/main.tf
- infrastructure/authentication/outputs.tf
- infrastructure/authentication/variables.tf
- infrastructure/main.tf
> Setup Cognito user pool for project tokens

- infrastructure/authentication/main.tf
- infrastructure/outputs.tf
- services/api/infrastructure/api/main.tf
> Give api access to project pool

- services/api/infrastructure/api/main.tf
- services/api/infrastructure/webhook_handler/main.tf
> Add policy actions for api

- services/api/infrastructure/webhook_handler/main.tf
> Expose the cognito environment variables to webhook handler

- services/api/src/Command/NewProjectCommand.php
- services/api/src/Handler/WebhookHandler.php
- services/api/src/Service/AuthTokenService.php
- services/api/src/Service/WebhookProcessorService.php
- services/api/src/Service/WebhookProcessorServiceInterface.php
- services/api/src/Webhook/Processor/CommitsPushedWebhookProcessor.php
- services/api/src/Webhook/Processor/JobStateChangeWebhookProcessor.php
- services/api/src/Webhook/Processor/WebhookProcessorInterface.php
- services/api/tests/Command/NewProjectCommandTest.php
- services/api/tests/Handler/WebhookHandlerTest.php
- services/api/tests/Service/AuthTokenServiceTest.php
- services/api/tests/Service/WebhookProcessorTest.php
- services/api/tests/Webhook/Processor/CommitsPushedWebhookProcessorTest.php
- services/api/tests/Webhook/Processor/JobStateChangeWebhookProcessorTest.php
> Move Cognito to the source of truth for token validation

- services/api/infrastructure/main.tf
- services/api/infrastructure/ref_metadata/main.tf
- services/api/infrastructure/ref_metadata/outputs.tf
- services/api/infrastructure/ref_metadata/variables.tf
> Add new table to store ref metadata

- services/api/src/Client/DynamoDbClient.php
> Fixing retrieving coverage percentage from metadata table

- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/src/Query/TotalTagCoverageQuery.php
- services/analyse/src/Query/TotalUploadsQuery.php
- services/analyse/tests/Query/__snapshots__/TagAvailabilityQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalUploadsQueryTest__testGetQuery with data set 0__1.txt
> Fix incorrect spacing on query responses after doctrine formatter change

- packages/clients/src/Client/Github/GithubAppClient.php
- packages/clients/src/Client/Github/GithubAppInstallationClient.php
- packages/clients/src/ClientsBundle.php
> Add retry support to GitHub client

- services/publish/infrastructure/publish/main.tf
> Ensure AWS account ID is available for publish service

- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/src/Service/QueryService.php
> Add additional logs when carrying forward and performing queries

- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/tests/Query/__snapshots__/TagAvailabilityQueryTest__testGetQuery with data set 0__1.txt
> Limit tag availability to 120 days to reduce overall response size

- services/analyse/src/Query/TagAvailabilityQuery.php
- services/analyse/tests/Query/__snapshots__/TagAvailabilityQueryTest__testGetQuery with data set 0__1.txt
> Further reduce tag availability length

- services/analyse/src/Query/Result/UploadedTagsCollectionQueryResult.php
- services/analyse/src/Query/Result/UploadedTagsQueryResult.php
- services/analyse/src/Query/UploadedTagsQuery.php
- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/tests/Query/TagAvailabilityQueryTest.php
- services/analyse/tests/Query/UploadedTagsQueryTest.php
- services/analyse/tests/Query/__snapshots__/TagAvailabilityQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/UploadedTagsQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
> Separate tag availability and convert it into a paginated query set using commit history as a filter

- packages/event/src/Model/IngestFailure.php
- packages/event/src/Model/IngestStarted.php
- packages/event/src/Model/IngestSuccess.php
- packages/event/src/Model/Upload.php
- packages/event/tests/Service/EventValidationServiceTest.php
> Add UUID event validation

- .github/get-packages.php
- .github/workflows/split-packages.yml
> Automatically split packages into read-only repositories

- .github/get-packages.php
- .github/workflows/split-packages.yml
> Tidy up splitting workflow

- .github/workflows/split-packages.yml
> Automatically publish release when pushing tags to split repositories

- .github/workflows/split-packages.yml
- packages/clients/composer.json
- packages/clients/composer.lock
- packages/configuration/composer.json
- packages/configuration/composer.lock
- packages/contracts/composer.json
- packages/contracts/composer.lock
- packages/event/composer.json
- packages/event/composer.lock
- packages/local/composer.json
- packages/local/composer.lock
- packages/message/composer.json
- packages/message/composer.lock
- packages/telemetry/composer.json
- packages/telemetry/composer.lock
> Remove unnecessary version in package json files

- .github/dependabot.yml
> Refactor dependabot config

- .github/dependabot.yml
> Update dependabot grouping and registry definitions

- .github/dependabot.yml
> Include packages registry

- .github/dependabot.yml
> Tidy up dependency grouping and names

- packages/clients/composer.json
- packages/clients/composer.lock
- packages/configuration/composer.json
- packages/configuration/composer.lock
- packages/contracts/composer.json
- packages/event/composer.json
- packages/event/composer.lock
- packages/local/composer.json
- packages/local/composer.lock
- packages/message/composer.json
- packages/message/composer.lock
- packages/telemetry/composer.json
- packages/telemetry/composer.lock
> Make sure all packages explicitly expose the required php version

- .github/dependabot.yml
> Prevent cyclical lock file bumps on interdependent packages

- services/publish/src/Service/MessagePublisherService.php
- services/publish/src/Service/Templating/CoverageTemplateEnvironmentFactory.php
> Tidy annotations

- packages/contracts/src/Event/Event.php
- packages/event/src/Model/UtilisationAmendment.php
> Add a new event to record utilisation of coverage analysis

- services/analyse/composer.lock
- services/api/composer.lock
- services/ingest/composer.lock
- services/orchestrator/composer.lock
- services/publish/composer.lock
Reverts coverage-robot/core#2023
> Revert "Bump the services-packages group across 5 directories with 7 updates"

- packages/configuration/src/Mock/MockEnvironmentService.php
- packages/configuration/src/Mock/MockEnvironmentServiceFactory.php
- packages/configuration/src/Mock/MockSettingService.php
- packages/configuration/src/Mock/MockSettingServiceFactory.php
- packages/configuration/src/Mock/MockTagBehaviourServiceFactory.php
> Add replacement mock factories for common configuration services

- packages/configuration/src/Mock/MockEnvironmentService.php
> Improve the variable handling in mock environment service

- packages/configuration/src/Mock/MockSettingService.php
> Use enum value for indexing and lookups in mock

- infrastructure/queue/main.tf
- infrastructure/routing/main.tf
- infrastructure/warehouse/main.tf
> Fix some minor code scanning issues

- services/analyse/src/Service/Diff/Github/GithubDiffParserService.php
- services/analyse/tests/Service/Diff/Github/GithubDiffParserServiceTest.php
> Handle binary files which don't have a patch from the Github API

- packages/event/tests/Handler/EventHandlerTest.php
> Fix incorrect PSR namespace

- packages/clients/composer.json
- packages/configuration/composer.json
- packages/contracts/composer.json
- packages/event/composer.json
- packages/local/composer.json
- packages/message/composer.json
- packages/telemetry/composer.json
> Update package constraints for supporting packages

- services/analyse/composer.json
- services/analyse/composer.lock
- services/api/composer.json
- services/api/composer.lock
- services/ingest/composer.json
- services/ingest/composer.lock
- services/orchestrator/composer.json
- services/orchestrator/composer.lock
- services/publish/composer.json
- services/publish/composer.lock
> Make php version constraint more explicit

- .github/workflows/publish.yml
- services/publish/.env
- services/publish/src/Enum/EnvironmentVariable.php
- services/publish/src/Service/Publisher/Github/GithubPullRequestCommentPublisherService.php
- services/publish/src/Service/Publisher/Github/GithubReviewPublisherService.php
- services/publish/tests/Service/Publisher/Github/GithubPullRequestCommentPublisherServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubReviewPublisherServiceTest.php
> Remove bot ID and replace it with the app id

- services/publish/src/Service/Publisher/Github/GithubPullRequestCommentPublisherService.php
- services/publish/src/Service/Publisher/Github/GithubReviewPublisherService.php
> Cast the integer app id into a string for type safe comparison

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/event.yml
- .github/workflows/infrastructure.yml
- .github/workflows/ingest.yml
- .github/workflows/local.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
> Allow ci to run on non-main target PRs

- services/publish/src/Service/Publisher/Github/GithubReviewPublisherService.php
- services/publish/tests/Service/Publisher/Github/GithubReviewPublisherServiceTest.php
> Fix PR reviews not clearing by use the graphql API to lookup authored and deletable reviews

- services/publish/src/Service/Publisher/Github/GithubReviewPublisherService.php
> Add check to skip if theres no comments

- services/orchestrator/src/Event/AbstractOrchestratorEventRecorderProcessor.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
> Prevent event being recorded when it causes the state of a event in the store to move from success to ongoing

- services/analyse/src/Event/UploadsFinalisedEventProcessor.php
- services/analyse/tests/Event/UploadsFinalisedEventProcessorTest.php
- services/publish/src/Service/Publisher/Github/GithubReviewPublisherService.php
- services/publish/tests/Service/Publisher/Github/GithubReviewPublisherServiceTest.php
> Continue to publish empty reviews to ensure existing reviews are clear as nessesary

- packages/message/src/PublishableMessage/PublishableLineCommentMessageCollection.php
> Handle empty publishable lines

- services/ingest/src/Client/BigQueryClientInterface.php
- services/ingest/src/Service/Persist/GcsPersistService.php
- services/ingest/tests/Service/Persist/GcsPersistServiceTest.php
> Harden a lot of the loading of coverage into BigQuery to improve back off and error handling behaviour

- services/ingest/src/Service/Persist/GcsPersistService.php
> Dont retry jobs which timeout

- services/publish/src/Service/Publisher/Github/GithubReviewPublisherService.php
- services/publish/tests/Service/Publisher/Github/GithubReviewPublisherServiceTest.php
> Make reviews more interactive

- services/analyse/src/Service/Diff/Github/GithubDiffParserService.php
- services/analyse/tests/Service/Diff/Github/GithubDiffParserServiceTest.php
> Support larger pull request diffs

- .gitignore
- packages/contracts/src/Environment/EnvironmentServiceInterface.php
- packages/contracts/src/Environment/Service.php
> Add service type as a method on environment contract

- packages/configuration/src/ConfigurationBundle.php
- packages/configuration/src/Service/EnvironmentService.php
- packages/configuration/tests/Service/EnvironmentServiceTest.php
> Add method and config parameters to specify service type at runtime

- packages/configuration/src/ConfigurationBundle.php
- packages/contracts/src/Environment/EnvironmentServiceInterface.php
> Add service function into environment service contract

- packages/configuration/src/ConfigurationBundle.php
- packages/configuration/src/Service/EnvironmentService.php
> No longer convert config parameter into enum

- packages/configuration/src/Mock/MockEnvironmentService.php
> Fix mock implementation

- packages/configuration/src/Mock/MockEnvironmentServiceFactory.php
> Update mock factory constructor

- services/analyse/tests/Client/BigQueryClientTest.php
- services/analyse/tests/Client/DynamoDbClientTest.php
- services/analyse/tests/Query/FileCoverageQueryTest.php
- services/analyse/tests/Query/LineCoverageQueryTest.php
- services/analyse/tests/Query/TagAvailabilityQueryTest.php
- services/analyse/tests/Query/TotalCoverageQueryTest.php
- services/analyse/tests/Query/TotalTagCoverageQueryTest.php
- services/analyse/tests/Query/TotalUploadsQueryTest.php
- services/analyse/tests/Query/UploadedTagsQueryTest.php
- services/api/tests/Client/CognitoClientTest.php
- services/api/tests/Command/NewProjectCommandTest.php
- services/api/tests/Controller/WebhookControllerTest.php
- services/api/tests/Service/UploadServiceTest.php
- services/api/tests/Webhook/Signature/Github/GithubWebhookSignatureServiceTest.php
- services/ingest/tests/Client/BigQueryClientTest.php
- services/ingest/tests/Service/Persist/GcsPersistServiceTest.php
- services/ingest/tests/Service/Persist/S3PersistServiceTest.php
- services/orchestrator/tests/Client/DynamoDbClientTest.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
- services/publish/tests/Service/Publisher/Github/GithubAnnotationPublisherServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubPullRequestCommentPublisherServiceTest.php
- services/publish/tests/Service/Publisher/Github/GithubReviewPublisherServiceTest.php
> Update tests using environment mock

- packages/clients/tests/Service/ObjectReferenceServiceTest.php
> Tweak object reference tests

- services/analyse/infrastructure/analyse/main.tf
- services/orchestrator/infrastructure/orchestrator/main.tf
- services/publish/infrastructure/publish/main.tf
> Add object reference bucket name into environment vars

- services/api/.env
- services/api/composer.json
- services/api/composer.lock
- services/api/config/bundles.php
- services/api/config/packages/clients.yaml
- services/api/infrastructure/api/main.tf
- services/api/infrastructure/event_listener/main.tf
- services/api/infrastructure/webhook_handler/main.tf
- services/api/src/Client/WebhookQueueClient.php
- services/api/symfony.lock
- services/api/tests/Client/WebhookQueueClientTest.php
> Create a simple object reference for webhook objects

- services/api/src/Client/WebhookQueueClient.php
- services/api/src/Handler/WebhookHandler.php
- services/api/tests/Client/WebhookQueueClientTest.php
- services/api/tests/Handler/WebhookHandlerTest.php
> Use webhook references when processing messages

- services/api/src/Handler/WebhookHandler.php
> Actually resolve the webhook reference instead of using the initial sqs body

- services/api/src/Client/WebhookQueueClient.php
- services/api/src/Handler/WebhookHandler.php
- services/api/tests/Client/WebhookQueueClientTest.php
> Move back to direct queueing over object reference

- services/api/src/Handler/WebhookHandler.php
- services/api/tests/Handler/WebhookHandlerTest.php
> Remove old code to handle object reference webhook messages

- infrastructure/routing/main.tf
> Disable the default API gateway endpoint

- infrastructure/routing/main.tf
Reverts coverage-robot/core#2136
> Enable the default API gateway endpoint

- services/api/php/conf.d/php.ini
> Disable powered by header

- services/api/src/Client/CognitoClient.php
- services/api/src/Client/CognitoClientInterface.php
- services/api/src/Command/NewProjectCommand.php
- services/api/tests/Client/CognitoClientTest.php
> [Part 1] Generate unique project id

- services/api/src/Client/CognitoClient.php
- services/api/src/Client/CognitoClientInterface.php
- services/api/src/Controller/GraphController.php
- services/api/src/Controller/UploadController.php
- services/api/src/Handler/WebhookHandler.php
- services/api/src/Model/Project.php
- services/api/src/Service/AuthTokenService.php
- services/api/src/Service/AuthTokenServiceInterface.php
- services/api/src/Service/UploadService.php
- services/api/src/Service/UploadServiceInterface.php
- services/api/tests/Client/CognitoClientTest.php
- services/api/tests/Controller/GraphControllerTest.php
- services/api/tests/Controller/UploadControllerTest.php
- services/api/tests/Handler/WebhookHandlerTest.php
- services/api/tests/Service/AuthTokenServiceTest.php
- services/api/tests/Service/UploadServiceTest.php
> [Part 2] Retrieve project ids during upload signing

- infrastructure/authentication/main.tf
- packages/contracts/src/Event/EventInterface.php
- packages/contracts/src/Event/ProjectAwareEventInterface.php
> [Part 3] Add project aware event contract with non-required project id property

- packages/event/src/Model/ConfigurationFileChange.php
- packages/event/src/Model/CoverageFailed.php
- packages/event/src/Model/CoverageFinalised.php
- packages/event/src/Model/IngestFailure.php
- packages/event/src/Model/IngestStarted.php
- packages/event/src/Model/IngestSuccess.php
- packages/event/src/Model/JobStateChange.php
- packages/event/src/Model/Upload.php
- packages/event/src/Model/UploadsFinalised.php
- packages/event/src/Model/UploadsStarted.php
- packages/event/src/Model/UtilisationAmendment.php
- packages/event/tests/Service/EventProcessorServiceTest.php
- packages/event/tests/Service/EventValidationServiceTest.php
- services/api/src/Webhook/Processor/JobStateChangeWebhookProcessor.php
> [Part 4] Add project id property as nullable on events

- packages/event/src/Model/JobStateChange.php
> Fix a type error in the state change model

- services/api/src/Webhook/Processor/CommitsPushedWebhookProcessor.php
- services/api/src/Webhook/Processor/JobStateChangeWebhookProcessor.php
- services/api/tests/Webhook/Processor/CommitsPushedWebhookProcessorTest.php
- services/api/tests/Webhook/Processor/JobStateChangeWebhookProcessorTest.php
- services/ingest/src/Handler/EventHandler.php
> [Part 5] Start propagating project id onto webhook triggered events and uploads

- services/orchestrator/src/Event/AbstractIngestEventProcessor.php
- services/orchestrator/src/Event/CoverageFailedEventProcessor.php
- services/orchestrator/src/Event/CoverageFinalisedEventProcessor.php
- services/orchestrator/src/Event/JobStateChangeEventProcessor.php
- services/orchestrator/src/Model/Finalised.php
- services/orchestrator/src/Model/Ingestion.php
- services/orchestrator/src/Model/Job.php
- services/orchestrator/src/Model/OrchestratedEventInterface.php
- services/orchestrator/tests/Client/DynamoDbClientTest.php
- services/orchestrator/tests/Event/AbstractIngestEventProcessorTestCase.php
- services/orchestrator/tests/Event/CoverageFailedEventProcessorTest.php
- services/orchestrator/tests/Event/CoverageFinalisedEventProcessorTest.php
- services/orchestrator/tests/Event/IngestFailureEventProcessorTest.php
- services/orchestrator/tests/Event/IngestSuccessEventProcessorTest.php
- services/orchestrator/tests/Event/JobStateChangeEventProcessorTest.php
- services/orchestrator/tests/Service/EventStoreServiceTest.php
> [Part 6] Populate project id from orchestrator events

- services/analyse/src/Event/UploadsFinalisedEventProcessor.php
- services/publish/src/Command/InvokeCommand.php
- services/publish/src/Handler/EventHandler.php
> [Part 7] Pass project ID into final events

- packages/contracts/src/Event/ProjectAwareEventInterface.php
> [Part 8] Make the project id required on events

- packages/event/src/Model/ConfigurationFileChange.php
- packages/event/src/Model/CoverageFailed.php
- packages/event/src/Model/CoverageFinalised.php
- packages/event/src/Model/IngestFailure.php
- packages/event/src/Model/IngestStarted.php
- packages/event/src/Model/IngestSuccess.php
- packages/event/src/Model/JobStateChange.php
- packages/event/src/Model/Upload.php
- packages/event/src/Model/UploadsFinalised.php
- packages/event/src/Model/UploadsStarted.php
- packages/event/src/Model/UtilisationAmendment.php
> [Part 9] Make project id non nullable on event models

- services/orchestrator/src/Model/Finalised.php
- services/orchestrator/src/Model/Ingestion.php
- services/orchestrator/src/Model/Job.php
> [Part 10] Use the project id instead of composite key for orchestrator event names

- infrastructure/warehouse/main.tf
- services/ingest/src/Service/BigQueryMetadataBuilderService.php
> [Part 11] Push upload id into bigquery

- infrastructure/warehouse/main.tf
> [Part 12] Change clustering of uploads to use project id

- services/analyse/src/Query/Trait/CarryforwardAwareTrait.php
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/LineCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalCoverageQueryTest__testGetQuery with data set 2__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/TotalTagCoverageQueryTest__testGetQuery with data set 2__1.txt
> Change carried forward coverage queries filters

- services/analyse/composer.json
- services/analyse/composer.lock
- services/api/composer.json
- services/api/composer.lock
- services/ingest/composer.json
- services/ingest/composer.lock
- services/orchestrator/composer.json
- services/orchestrator/composer.lock
- services/orchestrator/tests/Client/DynamoDbClientTest.php
- services/publish/composer.json
- services/publish/composer.lock
Reverts coverage-robot/core#2183
> Revert "Bump the services-production group across 5 directories with 9 updates"

- services/api/src/Controller/GraphController.php
- services/api/tests/Controller/GraphControllerTest.php
- services/api/tests/Controller/__snapshots__/RoutingSnapshotTest__testCurrentRoutingConfigurationMatchesSnapshot__1.txt
> Improve route validation for refs and provider matching

- packages/configuration/src/Service/SettingService.php
- packages/event/src/Service/EventProcessorService.php
- packages/local/src/Command/InvokeEventCommand.php
> Remove deprecated tagged iterator attribute and replace with autowire iterator

- services/api/src/Model/Webhook/WebhookInterface.php
- services/api/tests/Service/WebhookValidationServiceTest.php
> Handle webhook push events where the event time is in the future

- services/analyse/src/Query/FileCoverageQuery.php
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 0__1.txt
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 1__1.txt
- services/analyse/tests/Query/__snapshots__/FileCoverageQueryTest__testGetQuery with data set 2__1.txt
> Ensure limit parameter is applied correctly to the file coverage query

- services/analyse/src/Client/DynamoDbClient.php
- services/analyse/tests/Client/DynamoDbClientTest.php
> Add better handling for query result iterators which are serialized and deserialized from cache

- packages/clients/src/Client/Github/GithubAppClient.php
> Tweak timeouts and retries for GitHub clients

- services/analyse/infrastructure/analyse/main.tf
- services/analyse/src/Service/Carryforward/CarryforwardTagService.php
- services/analyse/src/Service/CoverageComparisonService.php
- services/analyse/src/Service/History/CommitHistoryService.php
- services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
- services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
> Decrease commit history page size and increase timeout of lambda

- packages/clients/src/Client/Github/GithubAppClient.php
> Further tweaks for timeouts and retries with github clients

- infrastructure/outputs.tf
> Tidy up outputs

- packages/clients/src/Client/Github/GithubAppClient.php
Seeing an unusual amount of errors when using the RetryableHttpClient. This PR moves back to the original Httplug discovery mechanism, and applies a retry plugin, instead of a retry client.
More retries and a timeout are still set, which is different than before.
```HTTP/2 stream 7 was not closed cleanly: PROTOCOL_ERROR (err 1) for "https://api.github.com/graphql"```
> Go back to using the original Httplug client with retry plugin

- infrastructure/certificate/main.tf
- infrastructure/certificate/outputs.tf
- infrastructure/certificate/variables.tf
- infrastructure/main.tf
- infrastructure/routing/main.tf
- infrastructure/routing/variables.tf
> Bring cert managed into terraform

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/contracts.yml
- .github/workflows/event.yml
- .github/workflows/ingest.yml
- .github/workflows/local.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
- services/analyse/docker-compose.yml
- services/analyse/infrastructure/analyse/variables.tf
- services/analyse/infrastructure/variables.tf
- services/api/docker-compose.yml
- services/api/infrastructure/api/variables.tf
- services/api/infrastructure/event_listener/variables.tf
- services/api/infrastructure/variables.tf
- services/api/infrastructure/webhook_handler/variables.tf
- services/ingest/docker-compose.yml
- services/ingest/infrastructure/ingest/variables.tf
- services/ingest/infrastructure/variables.tf
- services/orchestrator/docker-compose.yml
- services/orchestrator/infrastructure/orchestrator/variables.tf
- services/orchestrator/infrastructure/variables.tf
- services/publish/docker-compose.yml
- services/publish/infrastructure/publish/variables.tf
- services/publish/infrastructure/variables.tf
> Deploy services exclusively on PHP 8.4

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/clients.yml
- .github/workflows/configuration.yml
- .github/workflows/contracts.yml
- .github/workflows/event.yml
- .github/workflows/ingest.yml
- .github/workflows/local.yml
- .github/workflows/message.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
- .github/workflows/telemetry.yml
- services/analyse/composer.json
- services/analyse/composer.lock
- services/api/composer.json
- services/api/composer.lock
- services/ingest/composer.json
- services/ingest/composer.lock
- services/orchestrator/composer.json
- services/orchestrator/composer.lock
- services/publish/composer.json
- services/publish/composer.lock
> Stop running PHP 8.3 tests and remove support in services

- packages/clients/composer.json
- packages/configuration/composer.json
- packages/contracts/composer.json
- packages/event/composer.json
- packages/local/composer.json
- packages/message/composer.json
- packages/telemetry/composer.json
> [Part 4] Remove support PHP 8.3 in packages

- .github/workflows/split-packages.yml
> Run split packages CI job with PHP 8.4

- services/api/src/Controller/GraphController.php
- services/api/src/Service/BadgeService.php
- services/api/src/Service/BadgeServiceInterface.php
- services/api/tests/Controller/GraphControllerTest.php
> Add a not found state for coverage badges where the token did not relate to a project

- infrastructure/warehouse/main.tf
> Move loadable coverage bucket into europe-west4 region

- services/analyse/composer.lock
- services/api/composer.lock
- services/ingest/composer.lock
- services/orchestrator/composer.lock
- services/publish/composer.lock
> Manually update internal package dependency versions

- infrastructure/main.tf
- services/analyse/infrastructure/analyse/main.tf
- services/analyse/infrastructure/main.tf
- services/api/infrastructure/api/main.tf
- services/api/infrastructure/event_listener/main.tf
- services/api/infrastructure/main.tf
- services/api/infrastructure/webhook_handler/main.tf
- services/ingest/infrastructure/ingest/main.tf
- services/ingest/infrastructure/main.tf
- services/orchestrator/infrastructure/main.tf
- services/orchestrator/infrastructure/orchestrator/main.tf
- services/publish/infrastructure/main.tf
- services/publish/infrastructure/publish/main.tf
> Switch to s3 locking

- infrastructure/bucket/main.tf
> Fix warning in terraform config

- .github/workflows/analyse.yml
- .github/workflows/api.yml
- .github/workflows/infrastructure.yml
- .github/workflows/ingest.yml
- .github/workflows/orchestrator.yml
- .github/workflows/publish.yml
> Switch to OIDC for workflows

- services/analyse/src/Service/CoverageComparisonService.php
- services/analyse/src/Service/History/CommitHistoryService.php
- services/analyse/tests/Service/CoverageComparisonServiceTest.php
- services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
> Reduce the number of requested commits from GitHub API per page

- renovate.json
> Add labels to renovate config

- renovate.json
> Seperate PRs in different parts of the monorepo

- renovate.json
> Remove additional branch prefix for internal package PRs

- packages/clients/src/ClientsBundle.php
- packages/configuration/src/ConfigurationBundle.php
- packages/configuration/src/Setting/DefaultTagBehaviourSetting.php
- packages/configuration/tests/Service/CachingSettingServiceTest.php
- packages/configuration/tests/Service/ConfigurationFileServiceTest.php
- packages/configuration/tests/Service/EnvironmentServiceTest.php
- packages/configuration/tests/Service/SettingServiceTest.php
- packages/configuration/tests/Service/TagBehaviourServiceTest.php
- packages/configuration/tests/Setting/LineCommentTypeSettingTest.php
- packages/event/src/EventBundle.php
- packages/event/src/Model/Upload.php
- packages/event/src/Model/UploadsFinalised.php
- packages/event/tests/Service/EventValidationServiceTest.php
- packages/local/tests/Service/CustomPayloadEventBuilderTest.php
- packages/local/tests/Service/ExistingFixtureEventBuilderTest.php
- packages/local/tests/Service/ManualInputEventBuilderTest.php
- packages/message/src/Client/PublishClient.php
- packages/message/src/PublishableMessage/PublishableMessageCollection.php
- packages/message/tests/Service/MessageValidationServiceTest.php
- packages/telemetry/src/Model/Metric/Dimensions.php
- packages/telemetry/src/Model/Metric/Metadata.php
- packages/telemetry/src/Model/Metric/MetricDirective.php
- packages/telemetry/tests/Service/MetricServiceTest.php
> Bulk apply type declaration docblock rector rules
